"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools_v2."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools_v2


@tool(strict=False)
def v2_request_approval(run_id: str, plan_id: str, note: str = '') -> dict:
    """Record human approval of a checkpoint plan. Gated by an Omnigent ASK policy: this tool only runs after a human approves the prompt in the Omnigent UI.

    Args:
        run_id: First Fifty run id returned by start_run.
        plan_id: Plan id returned by submit_test_plan.
        note: Optional note.
    """
    return omni_tools_v2.v2_request_approval(run_id=run_id, plan_id=plan_id, note=note)
