"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools_v2."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools_v2


@tool(strict=False)
def v2_start_run() -> dict:
    """Start a CycleWise v2 run (checkpoints 50/100/150). Returns run_id, batches with roles, budgets.
    """
    return omni_tools_v2.v2_start_run()
