"""Generate Omnigent tool files (tools/python/<tool>.py) for each agent.

Omnigent directory bundles load tools from `<agent>/tools/python/*.py`, as
module-level `@tool` functions. ONE TOOL PER FILE, named after the tool:
Omnigent 0.16 grants a session the tool names taken from the file stems, so a
multi-tool file would be loaded but refused at dispatch ("not in the agent
spec's registered tool surface"). Each wrapper delegates to
cyclewise.tools.omni_tools so there is one implementation. Re-run after
changing omni_tools:  python omnigent/gen_tools.py
"""

import inspect
import os
import re
from pathlib import Path

from cyclewise.tools import omni_tools

ROOT = Path(__file__).parent / "cyclewise_lab"
AGENT_TOOLS = {
    # request_approval lives on the supervisor: an Omnigent ASK raised inside a sub-agent
    # session is never shown to the human (sub-agents are headless), so the run stalls.
    ".": ["start_run", "get_run_state", "request_approval", "evaluate_run"],
    "agents/evidence": ["list_cells", "early_feature_summary", "query_early_cycles", "list_citations",
                        "submit_hypothesis"],
    "agents/planner": ["check_budget", "preview_ranking", "submit_test_plan"],
    "agents/runner": ["execute_plan"],
    "agents/critic_safety": ["safety_scan", "get_run_state", "submit_critique"],
}
ARG_DOC = {
    "run_id": "CycleWise run id returned by start_run.",
    "batch": "Batch key, e.g. 'b1' or 'b2'.",
    "role": "Batch role: 'train' or 'eval'.",
    "plan_id": "Plan id returned by submit_test_plan.",
    "cell_ids": "Optional list of cell ids, e.g. ['b1c3'].",
    "signals": "Optional list of signals from qd, qc, ir, tavg, tmin, tmax, chargetime, glitch.",
    "min_cycle": "First cycle (>= 1).",
    "max_cycle": "Last cycle; must be <= 50.",
    "hypothesis": "Hypothesis JSON string.",
    "n_cells": "Number of cells requested.",
    "rule": "Executable rule JSON string.",
    "top": "How many top-ranked cells to return.",
    "plan_draft": "TestPlanDraft JSON string.",
    "flags": "Safety flags JSON string (list).",
    "note": "Optional note.",
    "critique": "CritiqueDraft JSON string.",
    "revisions_used": "Revisions already made for this batch.",
}


def render(names: list[str]) -> str:
    out = ['"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""',
           "", "__TYPING__", "from omnigent_client.tools import tool", "",
           "from cyclewise.tools import omni_tools", ""]
    for n in names:
        fn = getattr(omni_tools, n)
        sig = inspect.signature(fn)
        params, call, docs = [], [], []
        for p in sig.parameters.values():
            ann = p.annotation if isinstance(p.annotation, str) else p.annotation.__name__
            ann = re.sub(r"(\w+(?:\[\w+\])?) \| None", r"Optional[\1]", ann)
            default = "" if p.default is inspect.Parameter.empty else f" = {p.default!r}"
            params.append(f"{p.name}: {ann}{default}")
            call.append(f"{p.name}={p.name}")
            docs.append(f"        {p.name}: {ARG_DOC.get(p.name, p.name)}")
        summary = inspect.getdoc(fn).replace("\n", " ")
        doc = f'    """{summary}\n' + (("\n    Args:\n" + "\n".join(docs) + "\n") if docs else "") + '    """'
        # strict=False: strict schemas mark every parameter required, so a defaulted
        # argument (e.g. note="") left out by the model would be rejected.
        out += ["", "@tool(strict=False)", f"def {n}({', '.join(params)}) -> dict:", doc,
                f"    return omni_tools.{n}({', '.join(call)})", ""]
    text = "\n".join(out)
    typing_line = "from typing import Optional\n" if "Optional[" in text else ""
    return text.replace("__TYPING__\n", typing_line)


def write_atomic(path: Path, text: str) -> None:
    """Write via temp file + rename, so a running agent never imports a half-written tool."""
    tmp = path.with_suffix(".py.tmp")
    tmp.write_text(text)
    os.replace(tmp, path)


if __name__ == "__main__":
    for rel, names in AGENT_TOOLS.items():
        d = ROOT / rel / "tools" / "python"
        d.mkdir(parents=True, exist_ok=True)
        for old in d.glob("*.py"):  # drop stale files so the surface matches AGENT_TOOLS exactly
            if old.stem not in names:
                old.unlink()
        for n in names:
            write_atomic(d / f"{n}.py", render([n]))
        print("wrote", d, names)
