"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools


@tool(strict=False)
def evaluate_run(run_id: str) -> dict:
    """Score the committed selections against both baselines with bootstrap CIs.

    Args:
        run_id: First Fifty run id returned by start_run.
    """
    return omni_tools.evaluate_run(run_id=run_id)
