"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools


@tool(strict=False)
def start_run() -> dict:
    """Start a First Fifty run. Returns run_id and the batch plan (ids, roles, budget).
    """
    return omni_tools.start_run()
