"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools


@tool(strict=False)
def early_feature_summary(batch: str) -> dict:
    """Feature catalog plus the label-free distribution of each early feature in the batch.

    Args:
        batch: Batch key, e.g. 'b1' or 'b2'.
    """
    return omni_tools.early_feature_summary(batch=batch)
