"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools


@tool(strict=False)
def list_citations() -> dict:
    """The closed list of citation ids agents may use.
    """
    return omni_tools.list_citations()
