"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools


@tool(strict=False)
def list_cells(batch: str) -> dict:
    """Eligible cell ids, charging protocol, and QC status for a batch.

    Args:
        batch: Batch key, e.g. 'b1' or 'b2'.
    """
    return omni_tools.list_cells(batch=batch)
