"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""

from typing import Optional
from omnigent_client.tools import tool

from cyclewise.tools import omni_tools


@tool(strict=False)
def query_early_cycles(batch: str, cell_ids: Optional[list[str]] = None, signals: Optional[list[str]] = None, min_cycle: int = 2, max_cycle: int = 50) -> dict:
    """Per-cycle signals (qd, ir, tmax, chargetime, ...) for cycles min_cycle..max_cycle <= 50.

    Args:
        batch: Batch key, e.g. 'b1' or 'b2'.
        cell_ids: Optional list of cell ids, e.g. ['b1c3'].
        signals: Optional list of signals from qd, qc, ir, tavg, tmin, tmax, chargetime, glitch.
        min_cycle: First cycle (>= 1).
        max_cycle: Last cycle; must be <= 50.
    """
    return omni_tools.query_early_cycles(batch=batch, cell_ids=cell_ids, signals=signals, min_cycle=min_cycle, max_cycle=max_cycle)
