"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools


@tool(strict=False)
def submit_hypothesis(run_id: str, batch: str, hypothesis: str) -> dict:
    """Validate and record a Hypothesis JSON {features:[{name,direction,weight}], rationale, citations, label:"agent-generated"}. Returns the executable rule derived from it.

    Args:
        run_id: First Fifty run id returned by start_run.
        batch: Batch key, e.g. 'b1' or 'b2'.
        hypothesis: Hypothesis JSON string.
    """
    return omni_tools.submit_hypothesis(run_id=run_id, batch=batch, hypothesis=hypothesis)
