"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools_v2."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools_v2


@tool(strict=False)
def v2_feature_catalog() -> dict:
    """Checkpoint feature catalog (computed at 50, 100, 150) and the allowed citation ids.
    """
    return omni_tools_v2.v2_feature_catalog()
