"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools_v2."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools_v2


@tool(strict=False)
def v2_submit_hypothesis(run_id: str, batch: str, hypothesis: str) -> dict:
    """Validate and record the batch's scoring rule: JSON {features:[{name,direction,weight}], rationale, citations, label:"agent-generated"}; dq_logvar must be the base signal.

    Args:
        run_id: First Fifty run id returned by start_run.
        batch: Batch key, e.g. 'b1' or 'b2'.
        hypothesis: Hypothesis JSON string.
    """
    return omni_tools_v2.v2_submit_hypothesis(run_id=run_id, batch=batch, hypothesis=hypothesis)
