"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools


@tool(strict=False)
def get_run_state(run_id: str) -> dict:
    """Latest hypothesis, plan, result, critique and revised rule for a run (no labels of unrevealed cells).

    Args:
        run_id: CycleWise run id returned by start_run.
    """
    return omni_tools.get_run_state(run_id=run_id)
