"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools


@tool(strict=False)
def safety_scan(run_id: str, batch: str) -> dict:
    """Flag hot cells, IR jumps and missing sensors in cycles 2..50. Flags go to the human.

    Args:
        run_id: CycleWise run id returned by start_run.
        batch: Batch key, e.g. 'b1' or 'b2'.
    """
    return omni_tools.safety_scan(run_id=run_id, batch=batch)
