"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools


@tool(strict=False)
def submit_critique(run_id: str, batch: str, role: str, critique: str, revisions_used: int = 0) -> dict:
    """Validate a CritiqueDraft JSON {revise, reason, new_features, flagged_cells, next_experiment}. Revision is refused unless the pre-registered trigger fired on the train batch. Role and the revision count are read from config and the log; the role/revisions_used arguments are ignored.

    Args:
        run_id: First Fifty run id returned by start_run.
        batch: Batch key, e.g. 'b1' or 'b2'.
        role: Batch role: 'train' or 'eval'.
        critique: CritiqueDraft JSON string.
        revisions_used: Ignored; read from the log.
    """
    return omni_tools.submit_critique(run_id=run_id, batch=batch, role=role, critique=critique, revisions_used=revisions_used)
