"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools_v2."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools_v2


@tool(strict=False)
def v2_run_state(run_id: str) -> dict:
    """Where the run is: per batch, the next checkpoint, budget spent, revised rule, and the event list.

    Args:
        run_id: CycleWise run id returned by start_run.
    """
    return omni_tools_v2.v2_run_state(run_id=run_id)
