"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools_v2."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools_v2


@tool(strict=False)
def v2_submit_critique(run_id: str, batch: str, critique: str) -> dict:
    """After checkpoint 150: JSON {revise, reason, new_features, next_experiment}. Revision is refused unless the pre-registered trigger (Spearman < 0.5 on revealed cells) fired on a b1/b2 batch.

    Args:
        run_id: CycleWise run id returned by start_run.
        batch: Batch key, e.g. 'b1' or 'b2'.
        critique: CritiqueDraft JSON string.
    """
    return omni_tools_v2.v2_submit_critique(run_id=run_id, batch=batch, critique=critique)
