"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools


@tool(strict=False)
def check_budget(n_cells: int, batch: str) -> dict:
    """Check a request for n_cells against the per-batch cell budget.

    Args:
        n_cells: Number of cells requested.
        batch: Batch key, e.g. 'b1' or 'b2'.
    """
    return omni_tools.check_budget(n_cells=n_cells, batch=batch)
