"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools


@tool(strict=False)
def preview_ranking(batch: str, rule: str, top: int = 15) -> dict:
    """Score cells with an executable rule JSON and return the top of the ranking.

    Args:
        batch: Batch key, e.g. 'b1' or 'b2'.
        rule: Executable rule JSON string.
        top: How many top-ranked cells to return.
    """
    return omni_tools.preview_ranking(batch=batch, rule=rule, top=top)
