"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools


@tool(strict=False)
def submit_test_plan(run_id: str, batch: str, role: str, plan_draft: str, rule: str, flags: str = '[]') -> dict:
    """Validate a TestPlanDraft JSON {options:[>=2 {option_id, strategy, description, n_cells, n_explore, expected_learning}], chosen, reason}, fill cell ids from the rule, record it.

    Args:
        run_id: First Fifty run id returned by start_run.
        batch: Batch key, e.g. 'b1' or 'b2'.
        role: Batch role: 'train' or 'eval'.
        plan_draft: TestPlanDraft JSON string.
        rule: Executable rule JSON string.
        flags: Safety flags JSON string (list).
    """
    return omni_tools.submit_test_plan(run_id=run_id, batch=batch, role=role, plan_draft=plan_draft, rule=rule, flags=flags)
