"""Generated by omnigent/gen_tools.py; do not edit. Delegates to cyclewise.tools.omni_tools_v2."""

from omnigent_client.tools import tool

from cyclewise.tools import omni_tools_v2


@tool(strict=False)
def v2_submit_choice(run_id: str, batch: str, option_id: str, reason: str) -> dict:
    """Choose one option for the next checkpoint. Cell ids come from the ranking, never from the agent. Returns the plan (plan_id, cells to continue/keep, cells stopped) for the supervisor to approve.

    Args:
        run_id: First Fifty run id returned by start_run.
        batch: Batch key, e.g. 'b1' or 'b2'.
        option_id: Option id from v2_checkpoint_options, e.g. 'C'.
        reason: Why this option (>= 10 characters).
    """
    return omni_tools_v2.v2_submit_choice(run_id=run_id, batch=batch, option_id=option_id, reason=reason)
