"""v2 agents: Evidence (per batch), Planner (per checkpoint), Critic (per batch).

Same LLM layer as v1 (validation, retries with the error, labeled deterministic
fallback, response cache). The Planner chooses among budget-feasible options
generated by cyclewise.v2.allocation; it never writes cell ids or sizes.
"""

from __future__ import annotations

import json
from typing import Literal

from pydantic import BaseModel, Field, field_validator, model_validator

from cyclewise.agents import citations, llm
from cyclewise.config import load_config
from cyclewise.record import research_log
from cyclewise.v2.features import FEATURES

PROMPT_VERSION = "v2.0"


class FeatureW(BaseModel):
    name: str
    direction: Literal[-1, 1]
    weight: float = Field(1.0, gt=0, le=3)

    @field_validator("name")
    @classmethod
    def known(cls, v: str) -> str:
        if v not in FEATURES:
            raise ValueError(f"unknown feature {v!r}; choose from {sorted(FEATURES)}")
        return v


class EvidenceV2(BaseModel):
    features: list[FeatureW] = Field(min_length=1, max_length=5)
    rationale: str = Field(min_length=20)
    citations: list[str] = Field(min_length=1)
    label: Literal["agent-generated"] = "agent-generated"

    @model_validator(mode="after")
    def dq_is_base(self):
        dq = [f for f in self.features if f.name == "dq_logvar"]
        if not dq or dq[0].direction != -1:
            raise ValueError("pre-registered: dq_logvar (direction -1) must be the base signal")
        if dq[0].weight < max(f.weight for f in self.features):
            raise ValueError("pre-registered: dq_logvar must carry the largest weight")
        return self

    def rule(self) -> dict:
        return {"kind": "zscore_sum", "fit_on": "none",
                "weights": {f.name: f.direction * f.weight for f in self.features}}


class CheckpointChoice(BaseModel):
    chosen: str
    reason: str = Field(min_length=10)


class CritiqueV2(BaseModel):
    revise: bool
    reason: str = Field(min_length=10)
    new_features: list[str] = []
    next_experiment: str = ""

    @field_validator("new_features")
    @classmethod
    def known(cls, v: list[str]) -> list[str]:
        bad = [f for f in v if f not in FEATURES]
        if bad:
            raise ValueError(f"unknown features {bad}")
        return v


def _log(run_id, batch, agent, event, out, inputs, outcome):
    research_log.append(run_id, agent, event, out, batch=batch, inputs=inputs, model=outcome.model,
                        prompt_version=PROMPT_VERSION, fallback_used=outcome.fallback_used)


# ---------------------------------------------------------------- Evidence

EVIDENCE_SYSTEM = """You are the Evidence agent in First Fifty, a battery lab that decides at cycles 50,
100 and 150 which cells to keep testing. Pre-registered: log10 var(ΔQ_c) (Severson 2019) is the base
signal (direction -1, the largest weight). You may add up to 4 supporting features from the catalog
with smaller weights if you can justify them from published evidence. Cite only allowed ids. You see
no outcome labels."""


def evidence_fallback() -> EvidenceV2:
    return EvidenceV2(features=[FeatureW(name="dq_logvar", direction=-1, weight=1.0)], citations=["severson2019"],
                      rationale="Adopt Severson et al. 2019: log variance of ΔQ(V) is the strongest early "
                                "predictor of cycle life; the lab's contribution is allocation, not a new predictor.")


def evidence(run_id: str, batch: str, n_cells: int, critique: dict | None) -> EvidenceV2:
    prompt = (f"Batch {batch}, {n_cells} eligible cells. Catalog (computed at each checkpoint c):\n"
              + "\n".join(f"- {k}: {v['desc']} (prior {v['prior_sign']:+d})" for k, v in FEATURES.items())
              + f"\nAllowed citations: {sorted(citations.allowed())}\n"
              + (f"Last critique: {json.dumps(critique)}\n" if critique else ""))
    out = llm.complete(EvidenceV2, EVIDENCE_SYSTEM, prompt, fallback=evidence_fallback,
                       check=lambda h: citations.validate(h.citations))
    _log(run_id, batch, "evidence", "hypothesis", out.value.model_dump(), {"batch": batch}, out)
    return out.value


# ---------------------------------------------------------------- Planner

PLANNER_SYSTEM = """You are the Planner agent in First Fifty. At each checkpoint you choose ONE of the
listed allocation options (by option_id); all are within the channel-cycle budget. Trade-off:
continuing more cells costs cycles but lowers the chance of stopping a long-lived cell whose early
score was misleading. Cells that are clearly worst can be stopped early. At cycle 150 you choose how
the final cells kept to end of life are ranked. Give a short reason."""


def planner(run_id: str, batch: str, checkpoint: int, options: list[dict], context: dict) -> tuple[dict, str, bool]:
    ids = [o["option_id"] for o in options]

    def check(c: CheckpointChoice) -> None:
        if c.chosen not in ids:
            raise ValueError(f"chosen {c.chosen!r} is not one of {ids}")

    def fb() -> CheckpointChoice:
        # Deterministic policy. At 50 the budget split comes from the pre-registration
        # amendment (chosen on b1/b2 only); CYCLEWISE_V2_SPLIT overrides it for the dev sweep.
        # At 100: carry the planned number; at 150: the rule in force.
        pref = {50: default_split(), 100: "A", 150: "A"}[checkpoint]
        return CheckpointChoice(chosen=pref if pref in ids else ids[0],
                                reason=f"deterministic policy: split {default_split()} at 50, planned carry at 100, "
                                       "rule at 150")

    prompt = f"Checkpoint {checkpoint}, batch {batch}.\nContext: {json.dumps(context)}\nOptions:\n" + \
             "\n".join(json.dumps(o) for o in options)
    out = llm.complete(CheckpointChoice, PLANNER_SYSTEM, prompt, fallback=fb, check=check)
    opt = next(o for o in options if o["option_id"] == out.value.chosen)
    return opt, out.value.reason, out.fallback_used


# ---------------------------------------------------------------- Critic

CRITIC_SYSTEM = """You are the Critic in First Fifty. After a batch, a pre-registered trigger decides
whether the final-checkpoint scoring rule may be revised (never on the test batch). If revision is
permitted, choose a small feature list (about one feature per four revealed cells, dq_logvar first);
a tool fits the rule on revealed cells only. Always propose the next experiment."""


def critic(run_id: str, batch: str, permitted: bool, trigger: dict, revealed: list[dict],
           base_features: list[str], max_feats: int) -> CritiqueV2:
    def check(c: CritiqueV2) -> None:
        if c.revise and not permitted:
            raise ValueError("revision not permitted: trigger did not fire, or this is the test batch")
        if c.revise and not 1 <= len(c.new_features) <= max_feats:
            raise ValueError(f"choose 1..{max_feats} features")

    def fb() -> CritiqueV2:
        return CritiqueV2(
            revise=permitted,
            reason=("trigger fired: refit the final-checkpoint rule on revealed cells" if permitted else
                    "no revision: trigger did not fire" if not trigger["fired"] else
                    "trigger fired but revision is not permitted on this batch"),
            new_features=(["dq_logvar", *[f for f in base_features if f != "dq_logvar"]][:max_feats]
                          if permitted else []),
            next_experiment="Prospective run on new cells with the frozen v2 allocation policy; then a second chemistry.")

    prompt = (f"Batch {batch}. Trigger: {json.dumps(trigger)}. Revision permitted: {permitted}.\n"
              f"Revealed cells (kept to EOL or died in the paid window): {json.dumps(revealed, default=str)}\n")
    out = llm.complete(CritiqueV2, CRITIC_SYSTEM, prompt, fallback=fb, check=check)
    return out.value


def default_split() -> str:
    """Budget split at checkpoint 50: env override (dev sweep) > pre-registration amendment > 'B'."""
    import os
    from cyclewise import prereg
    env = os.environ.get("CYCLEWISE_V2_SPLIT")
    if env:
        return env
    amend = prereg.amendment()
    return (amend or {}).get("default_split_at_50", "B")


def prompt_version() -> str:
    return f"{PROMPT_VERSION}/{load_config()['agents']['prompt_version']}"
